const flavors =[
      { name: "Strawberry",
        family: "Fruits",
        type: "Soft Juicy",
        color: "Red",
        shape: "Heart",
        cutShape: "Slices, chopped",
        familiarity: "Very high",
        sweetness: "3",
        acidity: "3",
        flavourIntensity: "3",
        paring_comboCapacity: "4",
        aftertaste: "2",
        aroma: "1",
        texture: "soft",},
      { name: "Apple",
        family: "Fruits",
        type: "hard Juicy",
        color: "Red, Green, Yellow",
        shape: "Round Heart",
        cutShape: "Slices, OtherShapes",
        familiarity: "high",
        sweetness: "4",
        acidity: "2",
        flavourIntensity: "3",
        paring_comboCapacity: "1",
        aftertaste: "1",
        aroma: "1",
        texture: "firm Juicy",},
      { name: "Pineapple",
        family: "Fruits",
        type: "soft Juicy",
        color: "Yellow",
        shape: "Cylindrical",
        cutShape: "Slices, OtherShapes",
        familiarity: "Medium",
        sweetness: "3",
        acidity: "3",
        flavourIntensity: "4",
        paring_comboCapacity: "2",
        aftertaste: "3",
        aroma: "1",
        texture: "soft Juicy",},
    
]
export default flavors;
